### PR TITLE
refactored TypedSequence

### PR DESCRIPTION
**Pull request by xrotwang**

### CODE REVIEW

**Comment by xrotwang** [comment]
@LinguList I'm not sure if the "strict" behaviour is really needed. As far as I can tell, it may be rather confusing - e.g. if you concatenate strict and non-strict sequences, etc.

**Comment by LinguList** [comment]
Seems we won't need it! I am testing at the moment the new typedsequence. I think it is much, much better in this way.

It also helps to slim down lots of custom code in linse that I only wrote to maintain the problems with strings and plusses. Just found out, that one function in linse, where one returns a flat list out of a nested list of morphemes, can now just be ignored/deleted, since one can just use `itertools.chain(*w)` to get a representation of a word chained by all morphemes without boundary markers.

**Comment by LinguList** [comment]
One think I thought of is that we could add the possibility to segments to account for the slash notation that we use in lexibank and other cases (`t?/ts` for `t?` found in data and interpreted as `ts` by us).

**Review by LinguList — APPROVED** [review]
Very nice, I think this will help a lot for future development!

I have one suggestion regarding naming: should we call the `ints` and `floats` not `Integers` and `Floats`, to make sure they are a specific datatype (mainly capitals, as in Word, Morpheme)?

But this does not need to be done now, as it is more important to see where it would be needed and what exactly one wants.

**Pull request merged**
